### ISSUE TITLE
Scaling of UI elements in ipe 7.2.23 in Mac OS 11.2.1

### ISSUE THREAD

**Issue by mnoellenburg** [otfried/ipe#376] opened 2021-03-08 14:47 UTC
I have just updated to ipe 7.2.23 and the user interface has changed. Unfortunately, the icons are now at a larger scale and don't fit the width of a window, at least not on the MacBook screen. (See attached image, where the 7.2.20 version fits all icons and 7.2.23 drops many of them.) Is there any setting where I can modify the scale or go back to the old UI layout? 

I'm using the pre-compiled MacOS ipe-7.2.23-mac.dmg from ipe.otfried.org.

![Bildschirmfoto 2021-03-08 um 15 30 35](https://user-images.githubusercontent.com/26657460/110335002-ac6d7f80-8023-11eb-9d81-24863929f682.png)

**Comment by otfried** [comment] 2021-03-08 14:56
I noticed this too - it seems that El Sur changes the layout of the title (note that the toolbar and the title bar have now merged into one).
Are you running El Sur yourself?   Or is it just because I compiled on El Sur that one gets this?

**Comment by mnoellenburg** [comment] 2021-03-08 15:09
Yes, I’m using Big Sur myself. But the older ipe version doesn’t merge title bar and toolbar. I think I would actually prefer that if it’s an option.

**Comment by otfried** [comment] 2021-03-08 15:11
The problem is that I did not change anything at all in the source.  It's simply because it's compiled with the new compiler that the behaviour changed.   How does this work in other apps - do they all have the new layout in El Sur?

**Comment by mnoellenburg** [comment] 2021-03-08 15:27
Hmm, strange new behavior. Most apps in Big Sur have the new layout with the title bar only consuming a small part of each window on the top left. Others (less "shiny" apps) don't yet.

**Comment by otfried** [comment] 2021-03-08 16:40
I guess it depends if the app author has bothered to recompile the app with the newest Xcode.  It seems if you compile with an older compiler, you don't get the new behaviour.

I also seem to remember that before you could choose in the toolbar customization dialog if you wanted the large or the small icons.   Now you cannot choose anymore, you always get the large ones.

**Comment by otfried** [comment] 2021-03-08 16:45
Hmm, maybe it's just the default setting that has changed?

https://developer.apple.com/documentation/appkit/nswindowtitlevisibility

The toolbar docs still have pictures with the old layout:

https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/toolbars/

**Comment by otfried** [comment] 2021-04-07 08:52
Good news:  there is a new setting in 11.0 for the toolbar style:

https://developer.apple.com/documentation/appkit/nswindowtoolbarstyle/nswindowtoolbarstyleautomatic?language=objc

I will revert to the style we used until now in 7.2.24.

**Closed as completed by otfried** 2021-04-07 08:52 UTC
Labels: OSX
