### ISSUE TITLE
Keyboard shortcuts not working on Ubuntu

### ISSUE THREAD

**Issue by mloffler** [otfried/ipe#42] opened 2016-02-03 15:25 UTC
After upgrading from Ipe 7.1.9 to 7.2.1, half of the keyboard shortcuts stopped working for me. I now tried to upgrade to 7.2.2, but the problem persists.

Some keyboard shortcuts no longer work, while others do. The functions behind the broken shortcuts still work when I select them with the mouse (although some are not very useful this way, such as setting the origin (F1)).
In particular, as far as I can see, all shortcuts for toolbar buttons (such as tool selection, and the F4-F9 toggles) are still working. However, many other of the shortcuts to menu items (such as group, duplicate, send to front/back, save, creating views/pages, and shortcuts to ipelets) do not work. It is not exactly divided between toolbars / no toolbars though (interestingly, copy works but paste does not).

Since this has quite some impact and nobody else seems to have noticed, this may be an issue with my system. Nonetheless, I can't figure out what is wrong and this makes the latest versions unusable for me. Any idea what could be going on, or what I can do to fix this? Thanks!

I am running Ubuntu 14.04 LTS. I compiled Ipe from source. (No errors or warning during compilation, it looks the same as before.)

**Comment by otfried** [comment] 2016-02-03 15:37
Did you compile with Qt 4 or Qt 5?

**Comment by mloffler** [comment] 2016-02-03 15:41
```
qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
```

**Comment by otfried** [comment] 2016-02-03 15:47
I heard from several people that they had problems with Qt5 on Ubuntu 14.04, but they described a different problem (They do not see the main top menu, File Edit Properties etc.)

So one thing you could try is to compile with Qt4, see https://github.com/otfried/ipe-wiki/wiki/Downloading,%20Compiling,%20and%20Installing%20Ipe (the section "Debian, Ubuntu, Mint with Qt 4").

**Comment by mloffler** [comment] 2016-02-03 17:19
Ok, I compiled with Qt 4 and that indeed seems to solve the problem. Interestingly, I don't think I changed the Qt version between 7.1.9 and 7.2.1. In any case, thanks!

**Comment by otfried** [comment] 2016-02-03 18:10
Very strange.  Are you sure the last version were it worked correctly was 7.1.9?  That one only worked with Qt5.  7.1.8 was still using Qt4.

Did you perhaps change any of your shortcuts, either by modifying shortcuts.lua, or with a customization ipelet?

**Comment by mloffler** [comment] 2016-02-03 18:21
I am sure it was 7.1.9. I still have the sources in my downloads folder.

I do use custom shortcuts, but the first thing I tried when the problems appeared was to revert to the standard shortcuts.lua, and this didn't help (in particular, whether or not a shortcut worked seemed to be linked to the action, not the shotcut key).

**Comment by otfried** [comment] 2016-02-03 19:05
This is quite mysterious.  I just did a diff on the sources between 7.1.9 and 7.2.1 on the files related to shortcuts and could not find anything relevant.

And of course on my own system (Linux Mint with Qt 5.2.1) everything works...

**Comment by gillesbonnet** [comment] 2016-02-15 10:19
It seems that I have exactly the same problem.
I also installed Ipe 7.2.2 with qt 5.2.1 in ubuntu 14.04 LTS.
I checked the file ".../shortcut.lua". It seems that all the shortcuts are well defined there. But most of them just don't work. 
In the menus, some actions have written down keyboard shortcuts next to them ; it seems to be totally independent from the fact that the shortcut indicated there actually works or that it is written in the file ".../shortcut.lua". Some examples:
1) In ".../shortcut.lua" there is a line with `previous_view = "PgUp,"`, but the shortcut does not appear in the menu and does not work. 
2) In ".../shortcut.lua" there is a line with `last_view = "End",`, the shortcut appears in the menu but does not work. 
3) The shortcuts F4 to F9 appear both in  ".../shortcut.lua" and in the menus and are working.

**Comment by gillesbonnet** [comment] 2016-02-16 15:37
Seems to be related: https://bugs.launchpad.net/appmenu-qt5/+bug/1380702

**Comment by otfried** [comment] 2016-02-16 16:43
Yes, this seems to be caused by Ubuntu's changes to Qt themes.

One of the reasons I'm using Linux Mint...

**Comment by gillesbonnet** [comment] 2016-02-17 19:52
I reinstalled Ipe 7.2.2 with Qt4. That solved the problem for me as well.

**Comment by otfried** [comment] 2016-05-03 11:34
It seems the problem can also be fixed by removing the `appmenu-qt5` package, that is, do

```
sudo apt-get remove appmenu-qt5
```

**Comment by otfried** [comment] 2016-06-16 13:28
I've added an entry to the FAQ in the wiki.

**Comment by dietmarw** [comment] 2016-08-12 14:53
I was wondering if this issue should not be kept open. Even if there exists a workaround the underlying problem is not solved. Also removing appmenu-qt5 makes menus of other application look a bit strange and less integrated.

**Comment by otfried** [comment] 2016-08-13 09:41
That may be so, but it's pretty clearly not an Ipe bug. Ubuntu, in their misguided attempt to make their desktop look like OSX, hacked Qt to move menus elsewhere on the screen, and this just doesn't work correctly.  I would be happy to be told how Ipe can work around this Ubuntu bug, but ultimately it has to be fixed by Ubuntu.

**Comment by RichardSieg** [comment] 2016-09-12 13:34
I also have the same problem with 7.2.5 on 16.04. It compiles with QT_SELECT=5 but then I do not have any shortcuts whatsoever and with QT_SELECT=4 it does not compile.

**Comment by otfried** [comment] 2016-09-12 15:30
The bug still has not been fixed in Ubuntu, but it seems there is a workaround:

http://askubuntu.com/questions/742127/ctrl-shortcuts-not-working-in-vlc

All you have to do is to set the environment variable `QT_QPA_PLATFORMTHEME` to the empty string.

**Comment by otfried** [comment] 2016-09-12 15:32
If you do want to compile with Qt4, follow the instructions at https://github.com/otfried/ipe-wiki/wiki/Downloading,%20Compiling,%20and%20Installing%20Ipe#debian-ubuntu-mint-with-qt-4

**Comment by otfried** [comment] 2016-09-14 11:42
In 7.2.6 I will try to work around this problem by unsetting the environment variables `QT_QPA_PLATFORMTHEME` and `UBUNTU_MENUPROXY` when Ipe starts.

**Comment by otfried** [comment] 2016-09-24 18:32
@RichardSieg Have you tried compiling 7.2.6 with Qt5 yet?  Does my workaround fix the problem?

**Comment by RichardSieg** [comment] 2016-10-01 10:33
@otfried yes, it does. Thank you!

**Comment by otfried** [comment] 2016-10-05 21:03
Excellent.  I will close this now, finally.  Okay @dietmarw ?

**Comment by dietmarw** [comment] 2016-10-06 07:40
Yes it works fine with the snap version. So I'm OK with closing this one.

**Closed as completed** 2016-10-06 08:41 UTC
