### ISSUE TITLE
Transparency support in "Insert images from clipboard" [feature request]

### ISSUE THREAD

**Issue by Szepi** [otfried/ipe#311] opened 2020-05-08 16:59 UTC
Currently, the only way to insert images (if I am not mistaken) is to save them as a file, then add them. Adding figures would be much easier if there was support to paste images from the clipboard. 

Edit after double checking documentation: Hmm, the documentation says that this is already possible. I am using a Mac, tried to use this feature, and I get "nothing to paste".

**Comment by otfried** [comment] 2020-05-08 17:37
Indeed, copying bitmaps from the clipboard is implemented on Windows and Linux: just press Ctrl+V, and if the contents of the clipboard is an bitmap, that will be inserted.

On OSX, the problem is that i know how to read the image as an NSImage from the pasteboard, but that would need to be converted to a bitmap to be usable by Ipe.

I'll have to read this again: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CocoaDrawingGuide/Images/Images.html

In any case, I don't even own a modern Mac and do most OSX development on a virtual machine or somebody else's computer, so you'll see it's not easy for me to meet Mac user's wishes.

**Comment by Szepi** [comment] 2020-05-08 18:53
If you can be a bit more specific of the task, I can try to work out how to do this conversion:) [I am very tired of Powerpoint crashing on me:)]

**Comment by otfried** [comment] 2020-05-08 18:55
You should try Poweripe :-) 

https://github.com/otfried/ipe-tools/tree/master/poweripe

**Comment by otfried** [comment] 2020-05-08 18:58
The pasting code is this, all the way at the end of `appui_cocoa.cpp`:
```
int AppUi::clipboard(lua_State *L)
{
  // bool allow_bitmap = lua_toboolean(L, 2);
  // NSImage can be read in the same way, but I don't
  // know how to convert it to a bitmap...
  NSPasteboard *pasteBoard = [NSPasteboard generalPasteboard];
  NSArray *arr = [pasteBoard readObjectsForClasses:@[[NSString class]]
					   options:@{ } ];
  if (arr && [arr count] > 0) {
    lua_pushstring(L, N2C(arr[0]));
    return 1;
  }
  return 0;
}
```
I'm pretty sure that if you pass `[NSImage class]` as the argument to `readObjectsForClasses`, it will return to you an `NSImage` object.  What Ipe would then need is to convert that to bits:  width, height, and an array of ARGB values.

For instance, on Linux (Qt), the code looks like this:
```
static int getImage(lua_State *L, QImage &img)
{
  QImage im1 = img.convertToFormat(QImage::Format_ARGB32);
  int w = im1.width();
  int h = im1.height();
  Buffer data(w * h * sizeof(uint32_t));
  uint32_t *d = (uint32_t *) data.data();
  for (int y = 0; y < h; ++y) {
    uint32_t *p = (uint32_t *) im1.scanLine(y);
    for (int x = 0; x < w; ++x) {
      *d++ = *p++;
    }
  }

  Bitmap bitmap(w, h, Bitmap::ENative, data);
  Rect r(Vector::ZERO, Vector(w, h));
  Image *im = new Image(r, bitmap);
  push_object(L, im);
  return 1;
}

int AppUi::clipboard(lua_State *L)
{
  bool allow_bitmap = lua_toboolean(L, 2);
  QClipboard *cb = QApplication::clipboard();
  if (allow_bitmap) {
    QImage img = cb->image();
    if (!img.isNull()) {
      return getImage(L, img);
    }
  }
  QString data = cb->text();
  lua_pushstring(L, data.toUtf8());
  return 1;
}
```

**Comment by Szepi** [comment] 2020-05-09 01:01
Is the source code for IPE available? Can I access it somehow?
I was looking for it, but could not find it.
I guess I need to know what is the image object type that you want (Image, Bitmap: are these classes specific to IPE, or they are part of a library?).

**Comment by pierreganty** [comment] 2020-05-09 08:51
https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.16-src.tar.gz

**Comment by otfried** [comment] 2020-05-09 08:52
ipe.otfried.org -> Download -> May the source be with you.

Shouldn't be so hard to find :grinning:

**Comment by otfried** [comment] 2020-05-09 10:39
I figured out a way to do it:
```
      CGImageRef bitmap = [arr[0] CGImageForProposedRect:nil context:nil hints:nil];
```
Surprisingly one can just pass `nil` for all arguments and gets a nice bitmap when the input was a bitmap.   It doesn't seem to handle transparency or preserve jpeg-encoding for photos, but the Windows and Qt-versions do not do that either.

This will be in 7.2.17.

**Comment by Szepi** [comment] 2020-05-09 16:04
> https://dl.bintray.com/otfried/generic/ipe/7.2/ipe-7.2.16-src.tar.gz

That was lame of me; sorry.
Anyhow, I am very glad this got resolved this fast! Thanks!

**Comment by Szepi** [comment] 2020-05-09 22:15
Hmm, so the above code actually did not work that well. When it copies things, it somehow forgets the colormaps. I did some digging and came up with this code:
```
int AppUi::clipboard(lua_State *L)
{
  NSPasteboard *pasteBoard = [NSPasteboard generalPasteboard];
  bool allow_bitmap = lua_toboolean(L, 2);
  if (allow_bitmap) {
    NSBitmapImageRep *rep = (NSBitmapImageRep*)[NSBitmapImageRep imageRepWithPasteboard:pasteBoard];
    if (rep) {
      CGImageRef bitmap = [rep CGImage];
      // NSArray *arr = [pasteBoard readObjectsForClasses:@[[NSImage class]]
	// 				     options:@{ } ];
      // if (arr && [arr count] > 0) {
      // CGImageRef bitmap = [arr[0] CGImageForProposedRect:nil context:nil hints:nil];
      int w = CGImageGetWidth(bitmap);
      int h = CGImageGetHeight(bitmap);
      Buffer data(w * h * sizeof(uint32_t));
      if (cgImageDecode(bitmap, data)) {
	Bitmap bitmap(w, h, Bitmap::ENative, data);
	ipe::Rect r(Vector::ZERO, Vector(w, h));
	Image *im = new Image(r, bitmap);
	push_object(L, im);
	return 1;
      }
    }
  }
  [..]
}
```

This seems to be doing the trick! I think the key is to use NSBitmapImageRep because this will do a proper conversion to bitmaps whatever the source is.
I tested this and besides alpha, it seems to work.

**Comment by Szepi** [comment] 2020-05-09 23:21
Finally, to make alpha channels work, just modify `cgImageDecode` in `ipe_bitmapunix.cpp` to the following:

```
bool cgImageDecode(CGImageRef bitmap, Buffer pixelData)
{
  if (CGImageGetBitsPerComponent(bitmap) != 8)
    return false;

  int w = CGImageGetWidth(bitmap);
  int h = CGImageGetHeight(bitmap);
  int bits = CGImageGetBitsPerPixel(bitmap);
  int stride = CGImageGetBytesPerRow(bitmap);
  if (bits != 8 && bits != 24 && bits != 32)
    return false;
  int bytes = bits / 8;

  CGBitmapInfo info = CGImageGetBitmapInfo(bitmap);
  // Do we need to check for alpha channel, float pixel values, and byte order?
  ipeDebug("cgImageDecode: %d x %d x %d, stride %d, info %x", w, h, bytes, stride, info);

  CFDataRef pixels = CGDataProviderCopyData(CGImageGetDataProvider(bitmap));
  const uint8_t *inRow = CFDataGetBytePtr(pixels);

  uint32_t *q = (uint32_t *) pixelData.data();
  if (bits ==  24) {
    for (int y = 0; y < h; ++y) {
      const uint8_t *p = inRow;
      for (int x = 0; x < w; ++x) {
	*q++ = 0xff000000 | (p[0] << 16) | (p[1] << 8) | p[2];
	p += bytes;
      }
      inRow += stride;
    }
  }
  else if (bits ==  32) {
    for (int y = 0; y < h; ++y) {
      const uint8_t *p = inRow;
      for (int x = 0; x < w; ++x) {
  	*q++ = (p[3]<<24) | (p[0] << 16) | (p[1] << 8) | p[2];
  	p += bytes;
      }
      inRow += stride;
    }
  }
  else {
    for (int y = 0; y < h; ++y) {
      const uint8_t *p = inRow;
      for (int x = 0; x < w; ++x)
	*q++ = 0xff000000 | (*p << 16) | (*p << 8) | *p;
      inRow += stride;
    }
  }
  CFRelease(pixels);
  return true;
}
```

The modification is to split the 24 and 32 bit image sources; the 32 bit image source has the alpha channel in it, which we can just copy over to ipe's `Bitmap` as shown.
This works like charm.
Cheers,
  Csaba

**Comment by otfried** [comment] 2020-05-10 07:30
Sounds great, I'll put that in.

**Comment by otfried** [comment] 2020-05-10 08:07
What's a good way to test pasting images with alpha channel?

**Comment by Szepi** [comment] 2020-05-10 15:31
I just tried our university's [logo](https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FUniversity_of_Alberta&psig=AOvVaw33kHQsSUPVnck5mA91099q&ust=1589210926474000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCPCPt5jOqekCFQAAAAAdAAAAABAD).
Copied here:
![image](https://user-images.githubusercontent.com/5859662/81503421-c5d95a00-92a0-11ea-963f-cf64d716510e.png)

**Comment by otfried** [comment] 2020-05-10 16:45
Nice!

I should see if I can get the alpha-channel to work on other platforms as well.

**Comment by otfried** [comment] 2020-05-11 11:21
It turns out this has always worked with Qt.

On Windows, the clipboard seems to be a huge mess, with different programs advertising different formats on the clipboard.  One convention is to add a PNG format copy of the bitmap, so Ipe can now read that and use the transparency information.

**Closed as completed by otfried** 2020-05-11 11:21 UTC
