### ISSUE TITLE
Trying to run ipe on Arch Linux results in core dump

### ISSUE THREAD

**Issue by Sebas777-gif** [otfried/ipe#387] opened 2021-04-24 19:55 UTC
After installing ipe on Arch Linux today from the AUR, I cannot run it. When trying to run it, a core dump happens with the following message:

    /usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = ipe::String; _Alloc = std::allocator<ipe::String>; std::vector<_Tp, _Alloc>::reference = ipe::String&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
    [1]    113548 abort (core dumped)  ipe

Here is the full backtrace:

               PID: 130593 (ipe)
               UID: 1000 (sepo)
               GID: 1000 (sepo)
            Signal: 6 (ABRT)
         Timestamp: Sat 2021-04-24 21:32:08 CEST (21min ago)
      Command Line: ipe
        Executable: /usr/bin/ipe
     Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-org.kde.konsole-657c00478dc347d4af792789871547ac.scope
              Unit: user@1000.service
         User Unit: app-org.kde.konsole-657c00478dc347d4af792789871547ac.scope
             Slice: user-1000.slice
         Owner UID: 1000 (sepo)
           Boot ID: 6d89dcab819d4a46b01d0f3c260d0219
        Machine ID: 872f0013d78f420980397fb1de0530a8
          Hostname: hackerman2
           Storage: /var/lib/systemd/coredump/core.ipe.1000.6d89dcab819d4a46b01d0f3c260d0219.130593.1619292728000000.zst (present)
         Disk Size: 3.3M
           Message: Process 130593 (ipe) of user 1000 dumped core.
                    
                    Stack trace of thread 130593:
                    #0  0x00007fc82a1c8ef5 raise (libc.so.6 + 0x3cef5)
                    #1  0x00007fc82a1b2862 abort (libc.so.6 + 0x26862)
                    #2  0x000055e3a5315fcf n/a (ipe + 0x1bfcf)
                    #3  0x00007fc82b93bfff n/a (liblua5.3.so.5.3 + 0xefff)
                    #4  0x00007fc82b94972d n/a (liblua5.3.so.5.3 + 0x1c72d)
                    #5  0x00007fc82b93c3b8 n/a (liblua5.3.so.5.3 + 0xf3b8)
                    #6  0x00007fc82b93784c lua_callk (liblua5.3.so.5.3 + 0xa84c)
                    #7  0x00007fc82b959660 n/a (liblua5.3.so.5.3 + 0x2c660)
                    #8  0x00007fc82b93bfff n/a (liblua5.3.so.5.3 + 0xefff)
                    #9  0x00007fc82b94972d n/a (liblua5.3.so.5.3 + 0x1c72d)
                    #10 0x00007fc82b93c3b8 n/a (liblua5.3.so.5.3 + 0xf3b8)
                    #11 0x00007fc82b93b710 n/a (liblua5.3.so.5.3 + 0xe710)
                    #12 0x00007fc82b93c73b n/a (liblua5.3.so.5.3 + 0xf73b)
                    #13 0x00007fc82b93791a lua_pcallk (liblua5.3.so.5.3 + 0xa91a)
                    #14 0x000055e3a530cf82 n/a (ipe + 0x12f82)
                    #15 0x00007fc82a1b3b25 __libc_start_main (libc.so.6 + 0x27b25)
                    #16 0x000055e3a530d0be n/a (ipe + 0x130be)
                    
                    Stack trace of thread 130594:
                    #0  0x00007fc82a28037f __poll (libc.so.6 + 0xf437f)
                    #1  0x00007fc828f8e63b n/a (libxcb.so.1 + 0xc63b)
                    #2  0x00007fc828f9037b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                    #3  0x00007fc826b94161 n/a (libQt5XcbQpa.so.5 + 0x5e161)
                    #4  0x00007fc82a73f07f n/a (libQt5Core.so.5 + 0xce07f)
                    #5  0x00007fc829b60299 start_thread (libpthread.so.0 + 0x9299)
                    #6  0x00007fc82a28b053 __clone (libc.so.6 + 0xff053)
                    
                    Stack trace of thread 130598:
                    #0  0x00007fc829b6c9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                    #1  0x00007fc829b66260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                    #2  0x00007fc81c46aa1c n/a (iris_dri.so + 0x152a1c)
                    #3  0x00007fc81c464668 n/a (iris_dri.so + 0x14c668)
                    #4  0x00007fc829b60299 start_thread (libpthread.so.0 + 0x9299)
                    #5  0x00007fc82a28b053 __clone (libc.so.6 + 0xff053)
                    
                    Stack trace of thread 130595:
                    #0  0x00007fc82a28037f __poll (libc.so.6 + 0xf437f)
                    #1  0x00007fc829207ae8 n/a (libglib-2.0.so.0 + 0xa7ae8)
                    #2  0x00007fc8291b1781 g_main_context_iteration (libglib-2.0.so.0 + 0x51781)
                    #3  0x00007fc82a980191 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30f191)
                    #4  0x00007fc82a925fec _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b4fec)
                    #5  0x00007fc82a73de92 _ZN7QThread4execEv (libQt5Core.so.5 + 0xcce92)
                    #6  0x00007fc826ac7098 n/a (libQt5DBus.so.5 + 0x17098)
                    #7  0x00007fc82a73f07f n/a (libQt5Core.so.5 + 0xce07f)
                    #8  0x00007fc829b60299 start_thread (libpthread.so.0 + 0x9299)
                    #9  0x00007fc82a28b053 __clone (libc.so.6 + 0xff053)
                    
                    Stack trace of thread 130599:
                    #0  0x00007fc829b6c9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                    #1  0x00007fc829b66260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                    #2  0x00007fc81c46aa1c n/a (iris_dri.so + 0x152a1c)
                    #3  0x00007fc81c464668 n/a (iris_dri.so + 0x14c668)
                    #4  0x00007fc829b60299 start_thread (libpthread.so.0 + 0x9299)
                    #5  0x00007fc82a28b053 __clone (libc.so.6 + 0xff053)
                    
                    Stack trace of thread 130596:
                    #0  0x00007fc829b6c9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                    #1  0x00007fc829b66260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                    #2  0x00007fc81c46aa1c n/a (iris_dri.so + 0x152a1c)
                    #3  0x00007fc81c464668 n/a (iris_dri.so + 0x14c668)
                    #4  0x00007fc829b60299 start_thread (libpthread.so.0 + 0x9299)
                    #5  0x00007fc82a28b053 __clone (libc.so.6 + 0xff053)
                    
                    Stack trace of thread 130597:
                    #0  0x00007fc829b6c9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
                    #1  0x00007fc829b66260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
                    #2  0x00007fc81c46aa1c n/a (iris_dri.so + 0x152a1c)
                    #3  0x00007fc81c464668 n/a (iris_dri.so + 0x14c668)
                    #4  0x00007fc829b60299 start_thread (libpthread.so.0 + 0x9299)
                    #5  0x00007fc82a28b053 __clone (libc.so.6 + 0xff053)

**Comment by otfried** [comment] 2021-04-24 20:04
I'm afraid there is not enough information here for me to do anything about it.   I see you already report this on the AUR package, I hope they'll figure out what the problem is.

**Comment by Sebas777-gif** [comment] 2021-04-25 09:07
As someone wrote [here](https://bbs.archlinux.org/viewtopic.php?id=265788), it has to do with the recent addition of `-D_GLIBCXX_ASSERTIONS` to `makepkg.conf`. Since I really need to use ipe today, I fixed it by removing this from my `makepkg.conf` and building the package again. Just thought I'd give you this additional information (sorry if it was somehow already obvious, I'm still new).

**Comment by otfried** [comment] 2021-04-26 12:21
Thanks, this is helpful.

Fixed in 7.2.25.

**Closed as completed by otfried** 2021-04-26 12:21 UTC
