### ISSUE TITLE
Page sorter crashing or unresponsive

### ISSUE THREAD

**Issue by pierreganty** [otfried/ipe#281] opened 2020-01-14 11:37 UTC
Using 7.2.13 in Dark mode on OSX (Mojave 10.14.6) the page sorter sometimes become unresponsive (ok or cancel buttons have no effects) and I even experienced a crash while rearranging.

**Comment by otfried** [comment] 2020-04-18 07:59
I can only run Mojave on a virtual machine, so it's very hard for me to look into this.   Is there really a connection to dark mode?   Ipe doesn't contain any dark-mode specific code.    If you find a way to reproduce this reliably, please let me know.

**Comment by pierreganty** [comment] 2020-04-18 09:32
This is what I see if I open the page sorter of my latest talk.
Clicking on cancel or ok does nothing.

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2111160/79633945-e7469a80-8167-11ea-9496-0cdaf6cd77c7.png">

**Comment by otfried** [comment] 2020-04-19 13:36
Thanks for sending me the file.   I don't have Mojave, so I cannot try the dark mode, but I did find an uninitialized variable that could have caused this.   When you have a chance to try out the new release, can you check if the problem is fixed on 7.2.14?

**Comment by pierreganty** [comment] 2020-04-20 10:49
I just tried 7.2.14 and it seems to work now.

**Comment by otfried** [comment] 2020-04-20 11:00
Thanks for testing!

**Closed as completed by otfried** 2020-04-20 11:00 UTC
