### ISSUE TITLE
IPELATEXDIR setting in ipe.conf

### ISSUE THREAD

**Issue by WataruOhnishi** [otfried/ipe#242] opened 2019-04-24 05:59 UTC
I would like to set the `IPELATEXDIR` as follows:  
`IPELATEXDIR=./`  
to use `includegraphics` by the relative path. 

The setting in `ipe.conf` worked by ipe-7.2.7. However, it does not work by ipe-7.2.11. 
It would be great if I could set `IPELATEXDIR` in the latest version.

**Comment by otfried** [comment] 2019-04-24 11:06
Which platform are you using?   Windows?

I did not change the way `ipe.conf` is being handled - I think the problem is that your setting doesn't do what you expect it to do.   `./` is relative to the current working directory of the Ipe program.   This directory is not necessarily the directory in which the current Ipe document is located (and in fact you can edit a new Ipe document that does not even have a filename or a directory).

I think I should solve this problem differently, by adding the document directory to TEXINPUTS during the Latex run.

**Comment by WataruOhnishi** [comment] 2019-04-25 00:42
Thanks for the reply. The platform is Windows. 

I think `IPELATEXDIR` in the `ipe.conf` is somehow ignored by 7.2.11. Even if I set `IPELATEXDIR=C:\temp` (it exists), the temporary file is created in C:\Users\%USERNAME%\AppData\Local\ipe\ipetemp.tex. 
(The same setting works in 7.2.7)

**Comment by otfried** [comment] 2019-04-25 09:15
Thanks for the clarification - I found the bug.

It will be fixed in 7.2.12.

**Closed as completed** 2019-04-25 09:19 UTC
Labels: enhancement
