### ISSUE TITLE
Let Canvas keep a pointer to the document to avoid orphaned resources

### ISSUE THREAD

**Issue by tinloaf** [otfried/ipe#104] opened 2016-10-19 12:52 UTC
Hi,

**Update**
All of the debugging below boils down to: Ipe breaks if ipelets call model.doc:runLatex() directly. See my last comment. The question is whether this method should be removed from the Lua interface (forcing ipelets to go through model:runLatex()) or the C++ code should be fixed to set resources correctly.
**End of Update**

I'm trying to create an object via an Ipelet (that we've been using for ages) inside a template file (which we've been using for ages, too) - and I'm receiving a SIGSEGV. Everything works fine with older ipe versions.

The ipelet I'm using can be found here: http://i11www.iti.uni-karlsruhe.de/~barth/presentation.lua - the problematic function is the "Create Tabbed/Boxed Text" function (make sure to enter a title _and_ body, any string should do). It does work in empty ipe files, however not if I load our presentation template (see http://i11www.iti.uni-karlsruhe.de/~barth/kit-presentation.ipe )

I know that this is a very special combination of things; however, I failed to trace that error far enough to create a simpler example. Under https://gist.github.com/tinloaf/412a861525c5c348bb95c0045d98a99f you can find a backtrace of the crash (note that in that case, Ipe was compiled with -O0). I did a little digging, and at the bottom of that gist you can find what I think causes the problem: The iFonts->resources() seem to point to non-initialized data in the CairoPainter, note the bogus values when I try to print it. I'm not sure if the iFonts member even points to a valid Fonts instance (see the last two gdb commands of that gist), however these values are at least not obviously nonsense.

Why that's only the case if I load our presentation _and_ use that ipelet, I have no clue.

The ipelet itself runs until line 538, where it calls model:creation(). The XML of an example object to be created by the ipelet can be found at https://gist.github.com/tinloaf/b9fa127ab8839037e4e3bfa845fc63bd - this looks pretty boring actually.

I'd be happy to help with further debugging. My best guess at the moment is that something trashes the stack (because that iFonts->resources() _really_ should not be uninitialized, right?), but I fail to see how our ipelet could do that from inside a Lua VM...

Thanks for any help,

Lukas

**Comment by tinloaf** [comment] 2016-10-19 14:08
Some more debugging: I put a breakpoint on the creation of CairoPainters to see what Fonts objects are passed in. When starting ipe, four CairoPainters are created. Two of them have 0x0 passed in as Fonts-Pointer (I'm assuming that to be Okay..), two other calls seem to be passed pointers to valid Fonts objects. See this for example:

```
Thread 1 "ipe" hit Breakpoint 1, ipe::CairoPainter::CairoPainter (this=0x7fffffffce90, sheet=0xbdfd50, fonts=0xe6d910, cc=0xbdb4e0, zoom=2.1616915422885574, pretty=false)
    at ipecairopainter.cpp:264
264   iDimmed = false;
(gdb) p *(fonts)
$1 = {iResources = 0xe649a0, iFaces = {<std::__cxx11::_List_base<ipe::Face*, std::allocator<ipe::Face*> >> = {
      _M_impl = {<std::allocator<std::_List_node<ipe::Face*> >> = {<__gnu_cxx::new_allocator<std::_List_node<ipe::Face*> >> = {<No data fields>}, <No data fields>}, 
        _M_node = {<std::__detail::_List_node_base> = {_M_next = 0x1098620, _M_prev = 0xb11a70}, _M_data = 4}}}, <No data fields>}}
(gdb) p *(fonts->resources())
$2 = {iPageResources = std::unique_ptr<ipe::PdfDict> containing 0xe64a20, iObjects = std::unordered_map with 1178 elements = {
    [1169] = std::unique_ptr<const ipe::PdfObj> containing 0x1051b80, [581] = std::unique_ptr<const ipe::PdfObj> containing 0x1050cc0, 
    [1168] = std::unique_ptr<const ipe::PdfObj> containing 0x1050eb0, [580] = std::unique_ptr<const ipe::PdfObj> containing 0x104fff0, 
    [... lots of these ...]
```

When I run the ipelet, another CairoPainter is created:

```
Thread 1 "ipe" hit Breakpoint 1, ipe::CairoPainter::CairoPainter (this=0x7fffffffb8b0, sheet=0xbdfd50, fonts=0xe6d910, cc=0xbdb4e0, zoom=2.1616915422885574, pretty=false)
    at ipecairopainter.cpp:264
264   iDimmed = false;
(gdb) p *(fonts)
$5 = {iResources = 0xe649a0, iFaces = {<std::__cxx11::_List_base<ipe::Face*, std::allocator<ipe::Face*> >> = {
      _M_impl = {<std::allocator<std::_List_node<ipe::Face*> >> = {<__gnu_cxx::new_allocator<std::_List_node<ipe::Face*> >> = {<No data fields>}, <No data fields>}, 
        _M_node = {<std::__detail::_List_node_base> = {_M_next = 0x1098620, _M_prev = 0xb11a70}, _M_data = 4}}}, <No data fields>}}
(gdb) p *(fonts->resources())
$6 = {iPageResources = std::unique_ptr<ipe::PdfDict> containing 0x30c20b3d50adda78, 
  iObjects = std::unordered_map with -1630053799771508415 elements<error reading variable: Cannot access memory at address 0x14ba0a5ad263f264>, 
  iEmbedSequence = std::vector of length -1290162371340949818, capacity 1328649556031700870 = {<error reading variable>
```

Notice how it is being passed the same pointer as the earlier invocations, however now the values are all garbled. So I put a watchpoint on one of the addresses that becomes garbled (namely the iFonts->resources()->iPageResources variable), ran my ipelet, and:

```
Thread 1 "ipe" hit Hardware watchpoint 2: *0xe648c0

Old value = 15092032
New value = 0
std::unique_ptr<ipe::PdfDict, std::default_delete<ipe::PdfDict> >::~unique_ptr (this=0xe648c0, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:238
238       }
(gdb) bt
#0  std::unique_ptr<ipe::PdfDict, std::default_delete<ipe::PdfDict> >::~unique_ptr (this=0xe648c0, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:238
#1  0x00007ffff74c3486 in ipe::PdfResources::~PdfResources (this=0xe648c0, __in_chrg=<optimized out>) at ../include/iperesources.h:44
#2  0x00007ffff74c75c4 in ipe::Document::setResources (this=0xbe0f40, resources=0x11fbc70) at ipedoc.cpp:668
#3  0x00007ffff74c80e7 in ipe::Document::runLatex (this=0xbe0f40, texLog=...) at ipedoc.cpp:811
#4  0x00007ffff7745d55 in document_runLatex (L=0x66afe8) at ipelib.cpp:295
#5  0x00007ffff6f13090 in ?? () from /usr/lib/x86_64-linux-gnu/liblua5.3.so.0
[... more lines of the Lua stack plus Ipe ...]
```

Thus, it looks like the LaTeX run that my ipelet triggers (to measure some text height etc.) invalidates the pointer to the resources that are later (in model:creation()) being fed to the CairoPainter... I guess that the pointer to the (old, invalidated) resources is stored somewhere where it should be cleared and updated after a LaTeX run?

**Comment by tinloaf** [comment] 2016-10-19 17:41
Okay, lots of code-reading and getting to know Lua later: The problem is that the ipelet calls model.doc:runLatex() instead of model:runLatex(). The former _does_ update the resources of the document (thereby invalidating the old resources), but does _not_ update the resources of the canvas (because the model does not know about the canvas).

I originally intended to fix this by making the ipelet call model:runLatex(), but that had very weird effects which I could not explain. So I resorted to keeping the calls to model.doc:runLatex() in the code, but calling model:runLatex() after everything is done, making sure that all resources are properly set.

Now the question is: Should it be allowed for an ipelet to call model.doc:runLatex()? If so, the C++ code should somehow make sure that the resources inside the canvas are properly updated. If not, that method should probably not be exported to the Lua interface?

**Comment by otfried** [comment] 2016-10-19 21:03
All methods are available from Lua - there is no hiding (you can always access the global namespace through `_G` anyway).  

I guess you are simply the first to try running Latex from inside an Ipelet.   Have you tried doing it as follows:

```
model.doc:runLatex()
model.ui:setResources(model.doc)
```

By the way, you can achieve the effect of putting boxes around text much more easily now by using the `tcolorbox` environment.  E.g. put this in your preamble:

```
\usepackage{tcolorbox}
\tcbuselibrary{skins}
\newtcolorbox{block}[1]{enhanced,width=\textwidth,colbacktitle=blue!25!black,colback={blue!50},title={#1},drop fuzzy shadow,opacityfill=.5,colupper=white}
```

and then you can make nice boxes by creating a label object with the following contents:

```
\begin{block}{Theorem 1}
The world is flat.
\end{block}
```

**Comment by otfried** [comment] 2016-10-20 12:45
**Concrete answer:**

Yes, it's certainly fine to call `runLatex` on an Ipe document.  This doesn't have to be `model.doc` - you can also load a new Ipe document, or create one programmatically from scratch, and call `runLatex` on it.     So the C++ code cannot be "fixed" - it's perfectly fine to call `runLatex` on any document, and the C function implementing this Lua interface really has no idea about the canvas.

The problem arises when the ipelet returns without informing the canvas that the resources have changed.   Perhaps the canvas should simply know about the entire Ipe document (currently it only knows about a single page, for possible uses in editing pages outside of a document).

Currently (Ipe **7.2.6**), the correct procedure is this:

If you called `model.doc:runLatex()` inside the ipelet, then you **must** update the resources in the canvas by calling `model.ui:setResources(model.doc)`.   It's safest to do this immediately after calling `runLatex` (it's only necessary when the call succeeded).   If you do it later, it must be done before the UI is redrawn in any way, which happens inside the methods `explain`, `model:register`, `model:creation`, etc.

In the **future**:

I will change the Canvas class to keep a pointer to the Ipe document, so that it will always have the latest resources.   Nothing special needs to be done after running Latex.   The `setResources` method will disappear (so you'll have to update the ipelet again...).

In general, Ipe does not guarantee that mistakes in the Lua code do not crash the program.  (It's really not so easy to make such a guarantee.)

**Comment by otfried** [comment] 2016-10-20 13:07
Oops - what I said before doesn't work.  I will update the answer.

**Comment by tinloaf** [comment] 2016-10-21 08:06
Thanks a lot for the help! I somehow thought you'd need to export C functions to the Lua environment via lua_pushcfunction, so I thought it would be possible to "hide" document.runLatex(). However, I also fail to find these lua_pushcfunction calls..

In any case, our ipelet is working great again, but I think I'll actually be using tcolorbox from now on. Thanks for the great tip!

Should I leave this ticket open as a reminder for you to make the changes you described?

**Comment by otfried** [comment] 2016-10-21 08:23
`runLatex` is a method of the `doc` object - it's defined in the method table in the `ipelua` library.  This library has no access to the canvas (for instance, it's also used by `ipescript`, which has no user interface).

Yes, please leave the ticket open.   I'll close it when  I've implemented the change in `Canvas`.

**Comment by otfried** [comment] 2019-01-31 10:41
I decided not to make this change.   The problem is that it's not enough for the canvas to read the resources from the document:  we still need to create a new Fonts object whenever the resources have changed.   
Let's revisit this when implementing running Latex in the background - then I may need a versioning scheme for resources anyway.

**Closed as completed by otfried** 2019-01-31 10:41 UTC
Labels: enhancement
