### ISSUE TITLE
Graphics do not appear in PDF

### ISSUE THREAD

**Issue by taxipomme** [otfried/ipe#247] opened 2019-05-10 17:10 UTC
My Ipe version is Ipe 7.2.12
I inserted some PNG (with alpha chanel) using Insert Image (and resized them using precise strech). They appear well on the editor, seem to be saved in the PDF but do not appear when using Preview; Acrobat reader claims there is an error in the PDF. If I export from IPE as PNG everything is fine.
Using a PDF checker, the error seem to be "Could not find the XObject named 'Image11'."
The possibly relevant fragment of the PDF is:
(...)
11 0 obj <<
/Type /XObject
/Subtype /Image
/Width 126
/Height 640
/ColorSpace /DeviceGray
/Filter /FlateDecode
/BitsPerComponent 8
/Mask [0 0 0 0 0 0]
/Length 12702
>> stream
(...)
endstream endobj
(...)

**Comment by otfried** [comment] 2019-05-10 18:05
Could you attach the Ipe document?     If you don't want to share it here, you could also email it to me privately.

**Comment by taxipomme** [comment] 2019-05-10 18:07
I did not find how to attach it. Here it is. (there are 3 PNG hidden in the drawing ...)

Best,

Patrice

**Comment by otfried** [comment] 2019-05-10 18:20
There is no attachment.  You should be able to just drag the PDF file into the comment field.   If that doesn't work, please email it to me (`otfried@ipe.airpost.net`).

**Comment by taxipomme** [comment] 2019-05-10 18:21
Here you are.
[transduction.pdf](https://github.com/otfried/ipe-issues/files/3167672/transduction.pdf)

**Comment by otfried** [comment] 2019-05-10 18:47
Interesting:  xreader and evince on Linux show the file perfectly well, so does Chrome on Windows - but Acrobat Reader on Windows doesn't show the three bitmaps.

The PDF fragment above was spot-on: The problem is that Ipe produces the `/Mask` entry for the color key as an RGB value with three components, but since the image is grayscale, it should only be a single number (that is `/Mask [0 0]` ).

I will fix this soon (week of May 20).   The only workaround I can suggest now is to make the images colored (a single pixel that is not grayscale would suffice), or to remove the transparency (changing all transparent pixels to your background color white).   Or to edit the PDF file :grin:

**Comment by taxipomme** [comment] 2019-05-10 19:40
Thanks

**Comment by otfried** [comment] 2019-05-13 18:38
Fixed in 7.2.13.

**Closed as completed by otfried** 2019-05-13 18:38 UTC
